### ISSUE TITLE
Ignore fields that aren't indexed

### ISSUE THREAD

**Issue by petr-tik** [quickwit-oss/tantivy-cli#46]
Currently, passing a json file with fields that aren't indexable leads to an error like this

```bash
Failed to add document doc NoSuchFieldInSchema("asin")
```

I think it will be more user-friendly, if we ignore fields that we don't need to index and log it to stdout, instead of stopping indexing. This will reduce friction for new users - they will not have to change/preprocess their json files and can gradually add new fields and reindex.

**Comment by PSeitz** [comment]
That's the default now
