### ISSUE TITLE
What should be the schema for a non json log text file

### ISSUE THREAD

**Issue by savannahar68** [quickwit-oss/tantivy-cli#88]
Hi @fulmicoton 

I want to index and benchmark a text file containing millions of logs with each line having this structure

```
[Thu Jun 09 06:07:04 2005] [notice] LDAP: Built with OpenLDAP LDAP SDK
```

How can I define the schema for this file given schema is must with tantivy

**Comment by PSeitz** [comment]
Non-JSON is not supported in `tantivy cli`

The docs for tantivy (which does not have this limitation) are here:
https://docs.rs/tantivy/latest/tantivy/
